resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/16.yaml

packages:
- .

extra-deps:
- github: brendanhay/amazonka
  commit: 91eb47e8e8af0597b2c496d319fd19c0f7e47bc3
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/services/amazonka-cloudwatch
  - lib/services/amazonka-ecs
  - lib/services/amazonka-s3
  - lib/services/amazonka-secretsmanager
  - lib/services/amazonka-ses
  - lib/services/amazonka-sns
  - lib/services/amazonka-sqs
  - lib/services/amazonka-ssm
  - lib/services/amazonka-sso
  - lib/services/amazonka-sts
